{{- define "ffc-demo-web.container" -}}
name: {{ quote .Values.name }}
env:
- name: NODE_ENV
  value: {{ quote .Values.environment }}
- name: PORT
  value: {{ quote .Values.container.port }}
- name: COOKIE_PASSWORD
  value: {{ quote .Values.container.cookiePassword }}
- name: OKTA_DOMAIN
  value: {{ quote .Values.okta.domain }}
- name: OKTA_CLIENT_ID
  value: {{ quote .Values.okta.clientId }}
- name: OKTA_CLIENT_SECRET
  value: {{ quote .Values.okta.clientSecret }}
- name: OKTA_AUTH_SERVER_ID
  value: {{ quote .Values.okta.authorizationServerId }}
- name: SITE_URL
{{- if .Values.pr }}
  value: "{{ .Values.container.siteUrl }}-{{ .Values.pr }}.{{ .Values.ingress.server }}"
{{- else }}
  value: {{ quote .Values.container.siteUrl }}
{{- end }}
- name: REDIS_HOSTNAME
  value: {{ quote .Values.container.redisHostname }}
- name: REDIS_PARTITION
  value: {{ quote .Values.container.redisPartition }}
- name: REST_CLIENT_TIMEOUT_IN_MILLIS
  value: {{ quote .Values.container.restClientTimeoutMillis }}
- name: STATIC_CACHE_TIMEOUT_IN_MILLIS
  value: {{ quote .Values.container.staticCacheTimeoutMillis }}
- name: CLAIM_QUEUE_NAME
  value: {{ quote .Values.container.claimQueueName }}
- name: CLAIM_ENDPOINT
  value: {{ quote .Values.container.claimQueueEndpoint }}
- name: CLAIM_QUEUE_REGION
  value: {{ quote .Values.container.claimQueueRegion }}
- name: CREATE_CLAIM_QUEUE
  value: {{ quote .Values.container.claimCreateQueue }}
ports:
- containerPort: {{ .Values.container.port }}
  name: http
  protocol: TCP
livenessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.livenessProbe) | nindent 4 }}
readinessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.readinessProbe) | nindent 4 }}
{{- end -}}
