{{- include "adp-helm-library.container-secret" (list . "adp-demo-web.container-secret") -}}
{{- define "adp-demo-web.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
{{- end -}}
