{{- include "ffc-helm-library.service" (list . "ffc-demo-web.service") -}}
{{- define "ffc-demo-web.service" -}}
metadata:
  annotations:
  {{- if .Values.ingress.alb }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.endpoint }}.{{ .Values.ingress.server}}
  {{- end }}
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
  selector:
    {{- include "ffc-helm-library.selectorLabels" . | nindent 4 }}
{{- end -}}
