{{- include "ffc-helm-library.service" (list . "ffc-demo-web.service") -}}
{{- define "ffc-demo-web.service" -}}
metadata:
  annotations:
  {{- if .Values.ingress.alb }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.endpoint }}.{{ .Values.ingress.server}}
  {{- end }}
spec:
  ports:
  - port: {{ .Values.service.port}}
    name: http
    targetPort: http
  selector:
    {{- include "ffc-helm-library.selector-labels" . | nindent 4 }}
{{- end -}}
