apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ffc-demo-web"
  description: |
    Digital service mock to claim public money in the event property subsides into mine shaft.
    This is the web front end for the application. It contains a simple claim submission journey where user input data is cached in Redis.
    On submission the data is pulled from Redis and passed to the message service.
  annotations:
    github.com/project-slug: DEFRA/ffc-demo-web
    dev.azure.com/project: DEFRA-FFC
    dev.azure.com/build-definition: DEFRA.ffc-demo-web
    sonarqube.org/project-key: adp-ffc-demo-web
  tags:
    - node
    - service-bus
    - redis
    - external
    - front-end
spec:
  type: frontend
  lifecycle: beta
  owner: "group:default/fcp-demo"
  system: fcp-demo-service
  dependsOn:
    - "resource:default/fcp-demo-claim-queue"
    - "resource:default/ADPINFSB01"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fcp-demo-claim-queue
  description: Claims message queue
  tags:
    - azure-service-bus
    - queue
spec:
  type: message-queue
  owner: "group:default/fcp-demo"
  system: fcp-demo-service
  dependsOn: 
    - "resource:default/ADPINFSB01"
