version: '3'

# This override file should be used in development environments to
# bind-mount the app from the host into the container

services:
  ffc-poc-web:
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

volumes:
  node_modules:
