version: '3.7'

services:
  ffc-demo-web:
    build:
      context: .
      target: production
      args:
        REGISTRY: ${DOCKER_REGISTRY}
    image: ffc-demo-web
    environment:
      API_GATEWAY: http://ffc-demo-api-gateway:3001
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      REDIS_HOSTNAME: redis
