version: '3'
services:
  ffc-poc-web:
    build: .
    image: ffc-poc-web
    container_name: ffc-poc-web
    command: npm run start:watch
    depends_on:
      - ffc-poc-web-redis
    environment:
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      MINE_SUPPORT_API_GATEWAY: http://mine-support-api-gateway:3001
      REDIS_HOSTNAME: ffc-poc-web-redis
    networks:
      - ffc-poc-web-redis

  ffc-poc-web-redis:
    image: redis
    container_name: ffc-poc-web-redis
    networks:
      - ffc-poc-web-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


networks:
  ffc-poc-web-redis: {}

volumes:
  redis_data:
