services:
  ffc-demo-web:
    command: npm run start:watch
    build:
      target: development
    image: ffc-demo-web-development
    environment:
      NODE_ENV: test
    volumes:
      - ./test-output:/home/node/test-output

  zap-baseline-scan:
    image: softwaresecurityproject/zap-bare:2.14.0
    command: zap.sh -cmd -quickurl ${TEST_ENVIRONMENT_ROOT_URL:-http://ffc-demo-web:3000} -zapit ${TEST_ENVIRONMENT_ROOT_URL:-http://ffc-demo-web:3000} -configfile config/zap.conf -quickout test-output/zap-report.html -silent -quickprogress
    depends_on:
      - ffc-demo-web
    volumes:
      - ./test-output:/zap/test-output
      - ./zap:/zap/config
