version: '3.7'

services:
  ffc-demo-web:
    command: npm run start:watch
    build:
      target: development
    image: ffc-demo-web-development
    environment:
      NODE_ENV: test
    volumes:
      - ./test-output/:/home/node/test-output/

  axe:
    image: defradigital/ffc-axe
    depends_on:
      - ffc-demo-web
    command: sh -c "scripts/wait ffc-demo-web:3000 -- axe http://ffc-demo-web:3000/ --chromedriver-path=/usr/bin/chromedriver"
    volumes:
      - ./test-output/:/home/node/test-output/
      - ./scripts/:/home/node/scripts
