version: '3.7'

services:
  ffc-demo-web:
    build:
      context: .
      target: production
    image: ffc-demo-web
    depends_on:
      - redis
    environment:
      API_GATEWAY: http://ffc-demo-api-gateway:3001
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      REDIS_HOSTNAME: redis

  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  node_modules:
  redis_data:
