version: '3.7'

services:
  ffc-demo-web:
    command: npm run start:watch
    build:
      target: development
    image: ffc-demo-web-development
    environment:
      NODE_ENV: test
    volumes:
      - ./test-output/:/home/node/test-output/

  axe:
    image: defradigital/ffc-axe
    depends_on:
      - ffc-demo-web
    command: [http://ffc-demo-web:3000/, 
      http://ffc-demo-web:3000/claim/name, 
      http://ffc-demo-web:3000/claim/property, 
      http://ffc-demo-web:3000/claim/accessible, 
      http://ffc-demo-web:3000/claim/mine-type, 
      http://ffc-demo-web:3000/claim/date-of-subsidence, 
      http://ffc-demo-web:3000/claim/email, 
      http://ffc-demo-web:3000/claim/confirmation]
    volumes:
      - ./test-output/:/home/node/test-output/
