version: '3.7'

services:
  ffc-demo-web:
    build: .
    image: ffc-demo-web
    command: npm run start:watch
    depends_on:
      - redis
    environment:
      API_GATEWAY: http://ffc-demo-api-gateway:3001
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      REDIS_HOSTNAME: redis
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json

  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  node_modules:
  redis_data:
