version: '3'
services:
  ffc-demo-web:
    build: .
    image: ffc-demo-web
    container_name: ffc-demo-web
    command: npm run start:watch
    depends_on:
      - ffc-demo-web-redis
    environment:
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      API_GATEWAY: http://ffc-demo-api-gateway:3001
      REDIS_HOSTNAME: ffc-demo-web-redis
    networks:
      - ffc-demo-web-redis
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

  ffc-demo-web-css-watch:
    build: .
    image: ffc-demo-web
    command: npm run build:css-watch
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

  ffc-demo-web-redis:
    image: redis
    container_name: ffc-demo-web-redis
    networks:
      - ffc-demo-web-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


networks:
  ffc-demo-web-redis: {}

volumes:
  node_modules:
  redis_data:
