version: '3.7'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-demo-web:
    build:
      target: development
    image: ffc-demo-web-development
    environment:      
      APPINSIGHTS_CONSOLE_DEBUG_ENABLED: ${APPINSIGHTS_CONSOLE_DEBUG_ENABLED:-true}
    command: npm run start
    depends_on:
      - redis
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./test/:/home/node/test/
      - ./test-output/:/home/node/test-output/
      - ./scripts/:/home/node/scripts/
      - ./.git/:/home/node/.git/
      - ./jest.config.js:/home/node/jest.config.js
      - ./jest.setup.js:/home/node/jest.setup.js
      - ./package.json:/home/node/package.json
  redis:
    image: redis:4.0.14
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
