version: '3.7'

# This override file should be used to run automated tests in an
# isolated container stack

services:
  ffc-demo-web:
    command: npm run test
    volumes:
      - ./test/:/usr/src/app/test/
      - ./test-output/:/usr/src/app/test-output/
      - ./jest.config.js:/usr/src/app/jest.config.js
