version: '3.7'

# This override file should be used when running tests in CI pipelines
# to run tests against app code from the Docker image without binding
# ports to the host machine.

services:
  ffc-demo-web:
    build:
      target: development
    image: ffc-demo-web-development
    command: npm run test
    environment:
      NODE_ENV: test
      OKTA_DOMAIN: mydomain.otka.com
      OKTA_CLIENT_ID: placeholderclientid
      OKTA_CLIENT_SECRET: placeholdersecret
      OKTA_AUTH_SERVER_ID: placeholderauthserverid
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
      - ./test-output/:/home/node/test-output/
      - ./scripts/:/home/node/scripts/
