version: '3'

# This override file should be used in development environments to
# connect this service to sibling services from other repositories

services:
  ffc-poc-web:
    networks:
      - ffc-poc

networks:
  ffc-poc:
    external: true
