version: '3'

services:
  ffc-demo-web:
    build: .
    image: ffc-demo-web
    command: npm run start:watch
    depends_on:
      - redis
    environment:
      API_GATEWAY: http://ffc-demo-api-gateway:3001
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      REDIS_HOSTNAME: redis
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  node_modules:
  redis_data:
