version: '3'
services:
  ffc-demo-web:
    build: .
    image: ffc-demo-web
    container_name: ffc-demo-web
    command: npm run start:watch
    environment:
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      API_GATEWAY: http://ffc-demo-api-gateway:3001
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

volumes:
  node_modules:
