version: '3.7'

services:
  ffc-demo-web:
    build:
      context: .
      target: production
      args:
        REGISTRY: ${DOCKER_REGISTRY}
    image: ffc-demo-web
    environment:
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      REDIS_HOSTNAME: redis
      DEV_ACCESS_KEY_ID: elasticmq
      DEV_ACCESS_KEY: elasticmq
      CLAIM_QUEUE_NAME: claim
      CLAIM_QUEUE_URL: http://ffc-demo-claim-message-queue:9324/queue/claim
      CREATE_CLAIM_QUEUE: "true"
      CLAIM_ENDPOINT: http://ffc-demo-claim-message-queue:9324

  ffc-demo-claim-message-queue:
    image: softwaremill/elasticmq
