version: '3.4'

services:
  test:
    build:
      context: .
    environment:
      NODE_ENV: test
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      REDIS_HOSTNAME: not-accessed
    volumes:
      - ./test-output:/usr/src/app/test-output
    command: npm run test
