version: '3.7'

# This override file should be used when running tests in CI pipelines
# to run tests against app code from the Docker image without binding
# ports to the host machine.

services:
  ffc-demo-web:
    build:
      target: development
    image: ffc-demo-web-development
    command: npm test
    environment:
      NODE_ENV: test
    volumes:
      - ./test-output/:/home/node/test-output/
