version: '3'

# This override file should be used to run automated tests in an
# isolated container stack

services:
  ffc-demo-web:
    command: npm run test
    container_name: ffc-demo-web-test-${BUILD_NUMBER:-local}

  ffc-demo-web-redis:
    container_name: ffc-demo-web-test-redis-${BUILD_NUMBER:-local}
