version: '3.7'

# This override file should be used to run automated tests in an
# isolated container stack

services:
  ffc-demo-web:
    build:
      target: development
    command: npm run test
    volumes:
      - ./test/:/home/node/test/
      - ./test-output/:/home/node/test-output/
      - ./jest.config.js:/home/node/jest.config.js
