apiVersion: v1
appVersion: "1.0"
description: A Helm chart to deploy the FFC Demo Service sample application to Kubernetes
name: ffc-demo-web
# this version is automatically updated in the build pipline
version: 1.0.0
