environment: development
name: ffc-demo-web
namespace: ffc-demo
image: ffc-demo-web
workstream: ffc-demo

labels:
  component: web

containerConfigMap:
  name: ffc-demo-web-config-map

containerSecret:
  name: ffc-demo-web-container-secret
  type: Opaque

okta:
  clientSecret: secret

service:
  port: 80
  type: ClusterIP

secret:
  name: ffc-demo-basic-auth
  type: Opaque

serviceAccount:
  name: ffc-demo-web-service-account

container:
  redisHostname: redis-redis-ha.default
  redisPassword: redis
  redisPort: 6379
  redisPartition: ffc-demo
  imagePullPolicy: IfNotPresent
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 80Mi
  limitCpu: 80m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  restClientTimeoutMillis: 20000
  staticCacheTimeoutMillis: 54000
  port: 3000
  cookiePassword: passwordpasswordpasswordpasswordpassword
  claimQueueName: claim
  claimQueueEndpoint: http://ffc-demo-claim-message-queue:9324
  claimQueueRegion: eu-west-2
  claimCreateQueue: false

ingress:
  class: nginx
  endpoint: ffc-demo

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  redeployOnChange: update this field to force a change
  imagePullSecret:
  runAsNonRoot: true
  runAsUser: 1000

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
