environment: development
name: ffc-demo-web
namespace: ffc-demo
image: ffc-demo-web
workstream: ffc-demo

labels:
  component: web

secret:
  name: ffc-demo-basic-auth
  type: Opaque

auth:

container:
  redisHostname: redis-redis-ha.default
  redisPartition: ffc-demo
  imagePullPolicy: IfNotPresent
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 80Mi
  limitCpu: 80m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  apiGatewayUrl: http://ffc-demo-api-gateway.default
  restClientTimeoutMillis: 20000
  staticCacheTimeoutMillis: 54000
  port: 3000
  cookiePassword: passwordpasswordpasswordpasswordpassword

ingress:
  class: nginx
  endPoint: ffc-demo
  server:

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  redeployOnChange: update this field to force a change
  imagePullSecret:

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
