environment: development
name: ffc-demo-web
namespace: ffc-demo
image: ffc-demo-web
workstream: ffc-demo

appInsights:
  connectionString:

labels:
  component: web

container:
  memCpuTier: CUSTOM
  requestMemory: 50Mi
  requestCpu: 50m
  limitMemory: 200Mi
  limitCpu: 400m
  messageQueueHost: amq
  claimQueueAddress: claim
  protectiveMonitoringUrl:

ingress:
  class: nginx
  endpoint: ffc-demo
  server: example.com

deployment:
  priorityClassName: low
  minReadySeconds: 5
  useLinkerd: true

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3

aadWorkloadIdentity: true

serviceAccount:
  name: ffc-demo
  roleArn: true
