apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.component: {{ .Values.container.name }}
  name: {{ .Values.container.name }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicas }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy: {}
  template:
    metadata:
      labels:
        app.component: {{ .Values.container.name }}
      annotations:
        redeployOnChange: "{{ .Values.container.redeployOnChange }}"
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.image }}
        volumeMounts:
        - name: test
          mountPath: /kvmnt
          readOnly: true
        {{- if .Values.container.command }}
        {{- with .Values.container.command }}
        command:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.container.args }}
        args:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- end }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        env:
        - name: NODE_ENV
          value: {{ .Values.environment }}
        - name: PORT
          value: "3000"
        - name: COOKIE_PASSWORD
          value: {{ .Values.cookiePassword }}
        - name: REDIS_HOSTNAME
          value: {{ .Values.container.redisname }}
        - name: MINE_SUPPORT_API_GATEWAY
          value: {{ .Values.container.apiGatewayUrl }}
        - name: MINE_SUPPORT_MESSAGE
          valueFrom:
            secretKeyRef:
              name: mine-support-message
              key: message
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        resources:
            requests:
                memory: {{ .Values.container.requestMemory | quote }}
                cpu: {{ .Values.container.requestCpu | quote }}
            limits:
                memory: {{ .Values.container.limitMemory | quote }}
                cpu: {{ .Values.container.limitCpu | quote }}
      restartPolicy: {{ .Values.container.restartPolicy }}
      volumes:
      - name: test
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds                  # [OPTIONAL] not required if using Pod Identity
          options:
            usepodidentity: "false"        # [OPTIONAL] if not provided, will default to "false"
            keyvaultname: "minesupportkv"               # the name of the KeyVault
            keyvaultobjectnames: mine-support-message    # list of KeyVault object names (semi-colon separated)
            keyvaultobjecttypes: secret  # list of KeyVault object types: secret, key or cert (semi-colon separated)
            keyvaultobjectversions: ""     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
            resourcegroup: "MineSupportKV"              # the resource group of the KeyVault
            subscriptionid: "e08bae91-134c-42e6-a2e0-03bd58c350c4"             # the subscription ID of the KeyVault
            tenantid: "c532b08a-bbe0-4ecb-993c-935e38e9b535"                   # the tenant (Directory) ID of the KeyVault      
status: {}
