{{- if .Values.ingress.alb }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.serviceName }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.alb.arn}}
    alb.ingress.kubernetes.io/tags: {{ .Values.ingress.alb.tags }}
    external-dns.alpha.kubernetes.io/aws-zone-type-private: "true"
spec:
  rules:
{{- if .Values.ingress.endpoint }}
  - host: {{ .Values.ingress.endpoint }}.{{.Values.ingress.server}}
    http:
{{ else }}
  - http:
{{- end }}
      paths:
      - path: /*
        backend:
          serviceName: {{ .Values.ingress.serviceName }}
          servicePort: {{ .Values.service.port }}
{{- end }}
