apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Values.containers.redis.name }}
spec:
  serviceName: {{ .Values.containers.redis.name }}
  template:
    metadata:
      name: {{ .Values.containers.redis.name }}
      labels:
       name: {{ .Values.containers.redis.name }}
    spec:
      containers:
        - name: {{ .Values.containers.redis.name }}
          image: {{ .Values.containers.redis.image }}:{{ .Values.containers.redis.tag }}
          imagePullPolicy: {{ .Values.containers.redis.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.containers.redis.port }}
