namespaceQueues:
  - name: claim
    roleAssignments:
      - roleName: "QueueSender"

namespaceTopics:
  - name: claim-notify
    roleAssignments:
      - roleName: "TopicSender"

storageAccounts:
  - name: demoweb
    storageAccountsFileService:
      deleteRetentionPolicy:
        enabled: true
        days: 15
    blobContainers:
      - name: container-01
        roleAssignments:
          - roleName: "BlobDataContributor"
      - name: container-02
        roleAssignments:
          - roleName: "BlobDataReader"
    tables:
      - name: table01
        roleAssignments:
          - roleName: "TableDataContributor"
    fileShares:
      - name: share-01
      - name: share-02
        accessTier: Hot
        shareQuota: 50