namespaceQueues:
  - name: claim
    roleAssignments:
      - roleName: 'QueueSender'

namespaceTopics:
  - name: claim-notify
    roleAssignments:
      - roleName: 'TopicSender'

storageAccounts:
  - name: demoweb
    blobContainers:  
      - name: container-01
        roleAssignments:
          - roleName: 'BlobDataContributor' 
      - name: container-02
        roleAssignments:
          - roleName: 'BlobDataReader'   
    tables:  
      - name: table01  
        roleAssignments:
          - roleName: 'TableDataContributor'       