namespaceQueues:
  - name: claim
    roleAssignments:
      - roleName: 'QueueSender'

namespaceTopics:
  - name: claim-notify
    roleAssignments:
      - roleName: 'TopicSender'

storageAccounts:
  - name: demoweb
    roleAssignments:
      - roleName: 'DataReader'
    blobContainers:  
      - name: container-01
      - name: container-02  
    tables:  
      - name: table01      