namespaceQueues:
  - name: claim
    roleAssignments:
      - roleName: 'QueueSender'

namespaceTopics:
  - name: claim-notify
    roleAssignments:
      - roleName: 'TopicSender'

storageAccounts:
  - name: asostdebug150201
    blobContainers:  
      - name: container-01
  - name: asostdebug150202
    storageAccountsBlobService:
      containerDeleteRetentionPolicy:
        days: 15
        enabled: true
    blobContainers:  
      - name: container-01  