parameters:
  - name: runPerformanceTests
    displayName: Run Performance Tests
    type: boolean
    default: false

  - name: runAcceptanceTests
    displayName: Run Acceptance Tests
    type: boolean
    default: true

trigger: none

jobs:
- job: RunPerformanceTests
  condition: ${{  eq(parameters.runPerformanceTests, 'true') }}
  workspace:
    clean: all
  pool:
    vmImage: 'ubuntu-latest'  
  steps:
  - script: |
      cd test/performance
      docker-compose -f ../../docker-compose.yaml -f docker-compose.jmeter.yaml run jmeter-test
    displayName: Run Performance Tests

  # - task: CmdLine@2
  #   inputs:
  #     script: |
  #       echo "Structure of work folder of this pipeline:"
  #       tree $(Agent.WorkFolder)/1
  #       echo "Build.ArtifactStagingDirectory:" 
  #       echo "$(Build.ArtifactStagingDirectory)"
  #       echo "Build.BinariesDirectory:" 
  #       echo "$(Build.BinariesDirectory)"
  #       echo "Build.SourcesDirectory:"
  #       echo "$(Build.SourcesDirectory)"

  # - powershell: Get-ChildItem -Path '$(System.DefaultWorkingDirectory)' -recurse

  # - powershell: Get-ChildItem -Path '$(Agent.WorkFolder)' -recurse

  - task: CopyFiles@2
    displayName: Copy JMeter HTML Report
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/test-output/htmlreport'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/perf-tests'
      OverWrite: true
      flattenFolders: false

  - task: CopyFiles@2
    displayName: Copy JMeter Results (testresults.jtl)
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/test/performance'
      Contents: |
        testresults.jtl
      TargetFolder: '$(Build.ArtifactStagingDirectory)/perf-tests'
      OverWrite: false
      flattenFolders: true           

  - task: PublishPipelineArtifact@1
    displayName: Publish Performance Test Report
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)/perf-tests
      artifact: $(build.buildid)-perf-results

  - script: |
      JMETER_RESULTS=testresults.jtl
      JUNIT_RESULTS=testresults.xml
      python3 $(System.DefaultWorkingDirectory)/.azuredevops/scripts/jtl_junit_converter.py $JMETER_RESULTS $JUNIT_RESULTS
    workingDirectory: '$(Build.ArtifactStagingDirectory)/perf-tests'
    displayName: 'Convert JMeter Results to JUnit Format'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testRunTitle: 'FFC Demo Tests'
      testResultsFiles: '$(Build.ArtifactStagingDirectory)/perf-tests/testresults.xml'
      failTaskOnFailedTests: true
    displayName: 'Publish Load Testing Results'
  
  # - task: DownloadPipelineArtifact@0
  #   inputs:
  #     artifactName: $(build.buildid)-perf-results

  # - task: LakshayKaushik.PublishHTMLReports.publishhtmlreport.publishhtmlreport@1
  #   displayName: Publish Html Report
  #   inputs:
  #     htmlType: Jmeter
  #     JmeterReportsPath: '/test-output/htmlreport'


- job: RunAcceptanceTests
  condition: ${{ eq(parameters.runAcceptanceTests, 'true') }}
  workspace:
    clean: all
  pool:
    vmImage: 'ubuntu-latest'
  
  variables:
    - group: ffc-demo-web-acceptance-tests

  steps:

  - task: NodeTool@0
    displayName: 'Install Node.js v18'
    inputs:
      versionSpec: 'v18.x'
      checkLatest: true 
    enabled: true #this step takes long time to download nodejs file

  - script: |
      nvm list
      
      mkdir -p -m 777 /home/node/test-output
      mkdir -p -m 777 /home/node/html-reports/screenshots
      
      # start web application
      docker-compose up -d
      
      # run acceptance
      cd test/acceptance
      docker-compose run --rm wdio-cucumber
    displayName: Run Acceptance Tests

  - powershell: Get-ChildItem -Path '$(System.DefaultWorkingDirectory)' -recurse

  - powershell: Get-ChildItem -Path '$(Agent.WorkFolder)' -recurse    

  - task: CopyFiles@2
    displayName: Copy Acceptance HTML Report
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/test/acceptance/html-reports'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/acceptance-tests'
      OverWrite: true
      flattenFolders: false         

  - task: PublishPipelineArtifact@1
    displayName: Publish Acceptance Test Report
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)/acceptance-tests
      artifact: $(build.buildid)-acceptance-results

