apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:    
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: web-ingress
spec:
  rules:
  - http:
      paths:
      - path: /?(.*)
        backend:
          serviceName: web
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.component: web
  name: web
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app.component: web
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.component: web
  name: web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app.component: web
    spec:
      containers:      
      - name: mine-support-redis
        image: redis:latest
        ports:
        - containerPort: 6379
      - name: mine-support
        image: mine-support
        imagePullPolicy: Never
        env:                
        - name: NODE_ENV
          value: production
        - name: COOKIE_PASSWORD
          value: X9wSjhhiZNXk9dvQO1diJcpDUsfag44I
        ports:
        - containerPort: 3000               
      restartPolicy: Always
status: {}
