apiVersion: v1
appVersion: "1.0"
description: A Helm chart to deploy the Mine Support sample application to Kubernetes
name: helm
# this version is automatically updated in the build pipline
version: 1.0.0
