environment: development
image: mine-support
auth:
message: from a secret
service:
  port: 80

container:
  name: mine-support
  redisname: redis-redis-ha.default
  imagePullPolicy: IfNotPresent
  redeployOnChange: update this field to force a change
  requestMemory: 30Mi
  requestCpu: 10m
  limitMemory: 60Mi
  limitCpu: 50m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  apiGatewayUrl: http://mine-support-api-gateway.default
  restartPolicy: Always
ingress:
  serviceName: mine-support
  endPoint: mine-support
  server: vividcloudsolutions.co.uk
replicas: 2
minReadySeconds: 10
cookiePassword: passwordpasswordpasswordpasswordpassword
